const nogdb = require('nogdb');
let ctx = new nogdb.Context("test.db");
console.log("txn mode read write");
let txn = new nogdb.Txn(ctx,"1");
// console.log("TxnId" +" "+txn.getTxnId());
// console.log("verId" +" "+txn.getVersionId());
// console.log("Mode"  +" "+txn.getTxnMode());
// console.log("txn2 mode read only");
// let txn2 = new nogdb.Txn(ctx,"2");
// console.log("TxnId" +" "+txn2.getTxnId());
// console.log("verId" +" "+txn2.getVersionId());
// console.log("Mode"  +" "+txn2.getTxnMode());
// console.log("txn3 mode read only");
// let txn3 = new nogdb.Txn(ctx,"2");
// console.log("TxnId" +" "+txn3.getTxnId());
// console.log("verId" +" "+txn3.getVersionId());
// console.log("Mode"  +" "+txn3.getTxnMode());
// console.log("txn.rollback()"+" "+txn.rollback());
// // console.log("txn.commit()"+" "+txn.commit());
// console.log("txn4 mode read write");
// let txn4 = new nogdb.Txn(ctx,"1");
// console.log("TxnId" +" "+txn4.getTxnId());
// console.log("verId" +" "+txn4.getVersionId());
// console.log("Mode"  +" "+txn4.getTxnMode());
let dbinfo = new nogdb.DBInfo(txn);

